# Site settings
author: Eriberto Guzman
title: My Journey As A Software Engineer
header-img: img/home-bg.png
email: eriberto176@gmail.com
copyright_name: Eriberto Guzman
description: > # this means to ignore newlines until "baseurl:"
  Just the beginning
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Ejguzman3988

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
